version: 2
updates:
  - package-ecosystem: "npm" # pnpm is covered by the npm ecosystem
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
