allowBuilds:
  "@parcel/watcher": false
  esbuild: false
  msw: false
  sharp: false

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - msw
  - sharp

onlyBuiltDependencies:
  - esbuild
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vitest: 4.1.11
  vite-plus: 0.2.9
  "@vitest/coverage-v8": 4.1.10
  "@vitest/ui": 4.1.10
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
