/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsPokemonIndexRouteImport } from './routes/projects/pokemon/index'
import { Route as ProjectsPokemonIdentifierIndexRouteImport } from './routes/projects/pokemon/$identifier.index'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsPokemonIndexRoute = ProjectsPokemonIndexRouteImport.update({
  id: '/projects/pokemon/',
  path: '/projects/pokemon/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsPokemonIdentifierIndexRoute =
  ProjectsPokemonIdentifierIndexRouteImport.update({
    id: '/projects/pokemon/$identifier/',
    path: '/projects/pokemon/$identifier/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/projects/pokemon': typeof ProjectsPokemonIndexRoute
  '/projects/pokemon/$identifier': typeof ProjectsPokemonIdentifierIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/projects/pokemon': typeof ProjectsPokemonIndexRoute
  '/projects/pokemon/$identifier': typeof ProjectsPokemonIdentifierIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/projects/pokemon/': typeof ProjectsPokemonIndexRoute
  '/projects/pokemon/$identifier/': typeof ProjectsPokemonIdentifierIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/settings'
    | '/timeline'
    | '/projects/pokemon'
    | '/projects/pokemon/$identifier'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/settings'
    | '/timeline'
    | '/projects/pokemon'
    | '/projects/pokemon/$identifier'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/settings'
    | '/timeline'
    | '/projects/pokemon/'
    | '/projects/pokemon/$identifier/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SettingsRoute: typeof SettingsRoute
  TimelineRoute: typeof TimelineRoute
  ProjectsPokemonIndexRoute: typeof ProjectsPokemonIndexRoute
  ProjectsPokemonIdentifierIndexRoute: typeof ProjectsPokemonIdentifierIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/pokemon/': {
      id: '/projects/pokemon/'
      path: '/projects/pokemon'
      fullPath: '/projects/pokemon'
      preLoaderRoute: typeof ProjectsPokemonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/pokemon/$identifier/': {
      id: '/projects/pokemon/$identifier/'
      path: '/projects/pokemon/$identifier'
      fullPath: '/projects/pokemon/$identifier'
      preLoaderRoute: typeof ProjectsPokemonIdentifierIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SettingsRoute: SettingsRoute,
  TimelineRoute: TimelineRoute,
  ProjectsPokemonIndexRoute: ProjectsPokemonIndexRoute,
  ProjectsPokemonIdentifierIndexRoute: ProjectsPokemonIdentifierIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
