name: Deploy to Netlify

on:
  workflow_dispatch:

jobs:
  deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Deploy to Netlify
        run: pnpm dlx netlify-cli deploy --prod --build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
