name: E2E Tests

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  playwright:
    timeout-minutes: 15
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
      - uses: pnpm/action-setup@v6
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps
      - name: Run E2E tests
        run: pnpm test:e2e
        env:
          E2E_BASE_URL: ${{ (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && 'https://glennvisser.com' || '' }}
      - name: Upload HTML report
        uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: html-report--attempt-${{ github.run_attempt }}
          path: src/e2e-tests/test-reports
          retention-days: 7
